import path from "node:path";
import fs from "node:fs";

import { crx } from "@crxjs/vite-plugin";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

import manifest from "./src/extension/manifest";

export default defineConfig({
  plugins: [
    react(),
    {
      // Work around a CRX/Vite edge case where dynamically imported CSS (e.g. `katex.min-*.css`)
      // results in the manifest expecting a JS wrapper chunk (`katex.min-*.js`), but the wrapper
      // is not emitted into the Rollup bundle.
      //
      // We generate a tiny ESM wrapper that injects a <link> tag for the corresponding CSS file.
      name: "swiss-knife:ensure-katex-css-wrapper",
      generateBundle(_options, bundle) {
        const debug = process.env.SWISS_KNIFE_DEBUG_BUILD === "1";
        if (debug) {
          const katexFiles = Object.keys(bundle).filter((fileName) =>
            fileName.includes("katex")
          );
          console.log("[swiss-knife][debug] bundle katex files:", katexFiles);
        }

        // If CRX manifest validation can't find these files in the bundle (for reasons that can vary
        // by Vite/Rollup/plugin versions), it falls back to reading from disk under project root
        // or public dir. We proactively mirror the emitted files into `public/` so the fallback
        // path always succeeds.
        const katexMaybeFiles = Object.keys(bundle).filter((fileName) => {
          return (
            fileName.startsWith("assets/") &&
            fileName.includes("katex.min-") &&
            (fileName.endsWith(".js") || fileName.endsWith(".js.map"))
          );
        });
        if (katexMaybeFiles.length) {
          const publicRoot = path.resolve(__dirname, "public");
          for (const fileName of katexMaybeFiles) {
            const outPath = path.join(publicRoot, fileName);
            fs.mkdirSync(path.dirname(outPath), { recursive: true });
            const entry = bundle[fileName];
            const source =
              entry && entry.type === "chunk"
                ? entry.code
                : entry && "source" in entry
                  ? String(entry.source ?? "")
                  : "";
            fs.writeFileSync(outPath, source);
          }
        }

        const katexCssFiles = Object.keys(bundle).filter((fileName) => {
          return (
            fileName.startsWith("assets/") &&
            fileName.includes("katex.min-") &&
            fileName.endsWith(".css")
          );
        });

        for (const cssFileName of katexCssFiles) {
          const jsFileName = cssFileName.replace(/\.css$/, ".js");
          if (bundle[jsFileName]) continue;

          const source = [
            `// Auto-generated by swiss-knife to support KaTeX CSS loading in MV3 builds.`,
            `const href = new URL('./${path.posix.basename(cssFileName)}', import.meta.url).href;`,
            `if (typeof document !== 'undefined') {`,
            `  const exists = Array.from(document.querySelectorAll('link[rel="stylesheet"]')).some((l) => l.href === href);`,
            `  if (!exists) {`,
            `    const link = document.createElement('link');`,
            `    link.rel = 'stylesheet';`,
            `    link.href = href;`,
            `    document.head.appendChild(link);`,
            `  }`,
            `}`,
            `export {};`,
            ``
          ].join("\n");

          // Emit with an explicit filename so CRX manifest checks can find it.
          this.emitFile({ type: "asset", fileName: jsFileName, source });
        }
      }
    },
    crx({ manifest })
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
      "d3-sankey": path.resolve(__dirname, "src/shims/d3-sankey.ts")
    }
  },
  build: {
    outDir: "dist",
    // Avoid generating extra JS wrapper chunks for dynamically imported CSS (e.g. `katex.min-*.js`),
    // which can end up referenced by CRX web_accessible_resources but not emitted as a standalone file.
    cssCodeSplit: false,
    sourcemap: true
  }
});
